### ISSUE TITLE
Project 모듈 의존성 및 기능 개선

### ISSUE THREAD

**Issue by ShapeKim98** [ShapeKim98/Appteam04Onboard#3]
### 작업사항

- [x] 하위 모듈을 참조하기 위해 상위 모듈들을 import해야 하는 문제 해결하기
- [ ] ~~static 모듈들에 대한 preview 대응하기~~
- [x] 기능에 애니메이션 추가

**Comment by stealmh** [comment]
추가로 코드스타일도 `스타일쉐어`로 같이 정하는 것도 좋을 것 같아요!
https://github.com/StyleShare/swift-style-guide

저번에 말씀하셨던 변수, 함수명 네이밍도 컨벤션으로 맞출 수 있을 것 같아요 😆

**Comment by stealmh** [comment]
![스크린샷 2024-06-12 오후 3 29 14](https://github.com/ShapeKim98/Appteam04Onboard/assets/66459715/7bbf6143-d273-47b4-bee7-af7ca8085c64)

이슈 우측에 Development에 브랜치 < -- > 이슈도 연결해봅시다! <br> 
이렇게 설정해두고 PR날릴 때 최하단에는 close: #이슈번호 를 적어주면 <br>머지될 때 알아서 닫히더라구여 (1팀꺼 유심히 보고 배워옴🧐)

**Comment by ShapeKim98** [comment]
> ![스크린샷 2024-06-12 오후 3 29 14](https://private-user-images.githubusercontent.com/66459715/338847334-7bbf6143-d273-47b4-bee7-af7ca8085c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzQzNDAsIm5iZiI6MTcxODE3NDA0MCwicGF0aCI6Ii82NjQ1OTcxNS8zMzg4NDczMzQtN2JiZjYxNDMtZDI3My00N2I0LWJlZTctYWY3Y2E4MDg1YzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTQ4YjY2ZDJiZmUxMjg5ZTgzYjNlZmI0YjA4MmU1ZDk0M2JkNjU4OTIyNDhlZTU4YjdhOTQ5YjE5MmVkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISIytI1gDqcS1XnLYGJkTp0bFIolo1t_qSG00-GPf28)
> 
> 이슈 우측에 Development에 브랜치 < -- > 이슈도 연결해봅시다! 이렇게 설정해두고 PR날릴 때 최하단에는 close: #이슈번호 를 적어주면 머지될 때 알아서 닫히더라구여 (1팀꺼 유심히 보고 배워옴🧐)

오 넵

**Comment by ShapeKim98** [comment]
> 추가로 코드스타일도 `스타일쉐어`로 같이 정하는 것도 좋을 것 같아요! https://github.com/StyleShare/swift-style-guide
> 
> 저번에 말씀하셨던 변수, 함수명 네이밍도 컨벤션으로 맞출 수 있을 것 같아요 😆

네 좋습니다
